# Generated by Django 2.0 on 2020-02-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haw_book_manage', '0002_auto_20200215_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
