---
- name: Create AWS VPC to EC2 etc...
  hosts: localhost
  connection: local
  gather_facts: False
  roles:
    - ec2
  tasks:
    - name: Refresh inventory
      meta: refresh_inventory

- name: ec2 updating
  hosts: localhost
  user: ubuntu
  gather_facts: true
  roles:
    - update
    - middleware
